apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: securetask
data:
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
  KC_DB_USERNAME: securetask
  KC_DB_PASSWORD: change-me-for-local-development
  KC_HEALTH_ENABLED: "true"
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: change-me-for-local-development
